name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clear npm cache
        run: npm cache clean -f

      - name: Install dependencies
        run: npm install

      - name: Change working directory
        run: cd ../../

      - name: Build and test
        run: |
          npm run build
          npm test
